# Generated by Django 4.2.16 on 2026-06-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
