# Generated by Django 4.2.16 on 2026-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_repos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbadahLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='local_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
