# Generated by Django 4.2.16 on 2026-07-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ibadahlog_project_local_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_cache', to='core.project')),
            ],
        ),
    ]
