# Generated by Django 4.2.16 on 2026-07-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_githubcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_up', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('server', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('final_url', models.URLField(blank=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_checks', to='core.project')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
