# Generated by Django 4.2.16 on 2026-07-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_uptimecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='core.credential'),
        ),
        migrations.AddField(
            model_name='server',
            name='gcp_instance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='gcp_project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='gcp_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='provider',
            field=models.CharField(choices=[('gcp', 'GCP'), ('pdns', 'PDNS'), ('other', 'Lainnya')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='requires_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_alias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
