# Generated by Django 4.2.16 on 2026-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
