# Generated by Django 4.2.16 on 2026-07-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lockup_horizontal_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='lockup_vertical_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
