# Generated by Django 4.2.16 on 2026-09-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_command_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_min', models.IntegerField(default=25)),
                ('short_break_min', models.IntegerField(default=5)),
                ('long_break_min', models.IntegerField(default=15)),
                ('long_break_every', models.IntegerField(default=4)),
                ('auto_start_breaks', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('daily_target_sessions', models.IntegerField(default=8)),
                ('pause_for_prayer', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Focus settings',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_pomodoros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('focus', 'Focus'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='focus', max_length=20)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_min', models.IntegerField(default=25)),
                ('actual_sec', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('interrupted_by', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='core.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
