# Generated by Django 4.2.16 on 2026-09-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_focussettings_task_estimate_pomodoros_focussession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('reflection', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(blank=True, choices=[('daily', 'Every day'), ('weekdays', 'Every weekday'), ('weekly', 'Every week'), ('monthly', 'Every month')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_children', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='waiting_on',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='waiting_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
