# Generated by Django 4.2.16 on 2026-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_weeklyreview_task_completed_at_task_is_waiting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', models.OrderBy(models.F('due_date'), nulls_last=True), '-created_at']},
        ),
    ]
