# Generated by Django 4.2.16 on 2026-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='today_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
