# Generated by Django 4.2.16 on 2026-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_task_today_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAccountCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
